import re

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


def _bib_key(paper_id: str, title: str) -> str:
    """Generate a clean BibTeX key from paper id and title."""
    slug = re.sub(r"[^a-zA-Z0-9]", "", title.split()[0] if title else "paper")
    return f"{slug[:20]}_{paper_id[:8]}"


def _escape(value: str) -> str:
    return value.replace("{", "{{").replace("}", "}}").replace("\\", "\\\\")


def _format_authors(authors: list) -> str:
    if not authors:
        return "Unknown"
    return " and ".join(str(a) for a in authors)


async def generate_bibtex(db: AsyncSession) -> str:
    rows = await db.execute(
        text(
            "SELECT id, title, authors, year, arxiv_url "
            "FROM papers "
            "ORDER BY year DESC NULLS LAST, title"
        )
    )
    papers = rows.mappings().all()

    entries = []
    for paper in papers:
        key = _bib_key(str(paper["id"]), str(paper["title"] or ""))
        title = _escape(str(paper["title"] or "Untitled"))
        authors = _format_authors(paper["authors"] or [])
        year = str(paper["year"]) if paper["year"] else "0000"
        url = str(paper["arxiv_url"] or "")
        note = f"arXiv:{paper['id']}" if not paper["arxiv_url"] else ""

        lines = [
            f"@article{{{key},",
            f"  title   = {{{title}}},",
            f"  author  = {{{authors}}},",
            f"  year    = {{{year}}},",
        ]
        if url:
            lines.append(f"  url     = {{{url}}},")
        if note:
            lines.append(f"  note    = {{{note}}},")
        lines.append("}")
        entries.append("\n".join(lines))

    header = "% Generated by Lumen — https://github.com/lumen\n\n"
    return header + "\n\n".join(entries)
